#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## Script To Manage Speaker Volume For Archcraft (in Wayland).
iDIR="$HOME/.config/hypr/mako/icons"

# Get Volume
get_volume() {
	volume=$(pamixer --get-volume)
	echo "$volume"
}

# Get icons
get_icon() {
	vol="$(get_volume)"
	current="${vol}"
	if [[ "$current" -eq "0" ]]; then
		icon="$iDIR/volume-mute.png"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		icon="$iDIR/volume-low.png"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		icon="$iDIR/volume-mid.png"
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		icon="$iDIR/volume-high.png"
	fi
}

# Notify
notify_user() {
  get_icon
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Громкость : $(get_volume)%"
}

# Increase Volume
inc_volume() {
  pamixer --increase 5
  notify_user
}

# Decrease Volume
dec_volume() {
  pamixer --decrease 5
  notify_user
}

# Toggle Mute
toggle_mute() {
	pamixer --toggle-mute
	isMute=$(pamixer --get-mute)
	if [[ $isMute == "true" ]]; then
		icon="$iDIR/volume-mute.png"
		notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Громкость : 0%"
	else
		get_icon
		notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Громкость : $(get_volume)%"
	fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle-mute" ]]; then
	toggle_mute
else
	get_volume
fi